CREATE TABLE PAIS 
(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(200),
	CODIGO_IBGE INT
);

CREATE TABLE UF
(
	ID SERIAL PRIMARY KEY,
	ID_PAIS INT REFERENCES PAIS(ID),
	DESCRICAO VARCHAR(200),
	CODIGO_IBGE INT
);

CREATE TABLE CIDADE 
(
	ID SERIAL PRIMARY KEY,
	ID_UF INT REFERENCES UF(ID),
	DESCRICAO VARCHAR(200),
	CODIGO_IBGE INT
);

CREATE TABLE LOCAL 
(
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(50),
	CAPACIDADE INT, 
	ENDERECO VARCHAR(200),
	OBSERVACOES VARCHAR(2000),
	ID_CIDADE INT REFERENCES CIDADE(ID)
);

CREATE TABLE TIPO_EVENTO 
(
	ID SERIAL PRIMARY KEY, 
	DESCRICAO VARCHAR(200)
);

CREATE TABLE EVENTO 
(
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(2000),
	ID_LOCAL INT REFERENCES LOCAL(ID),
	ID_TIPO INT REFERENCES TIPO_EVENTO(ID)
);

CREATE TABLE AVALIACAO 
(
	ID SERIAL PRIMARY KEY, 
	COMENTARIO VARCHAR(2000),
	TIPO_ACESSIBILIDADE VARCHAR(1),
	TIPO VARCHAR(1),
	ID_LOCAL INT REFERENCES LOCAL(ID)
);

CREATE TABLE USUARIO 
(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50),
	EMAIL VARCHAR(100),
	SENHA VARCHAR(100)
);

CREATE TABLE RESPONSAVEL_LOCAL 
(
	ID SERIAL PRIMARY KEY, 
	ID_LOCAL INT REFERENCES LOCAL(ID),
	ID_USUARIO INT REFERENCES USUARIO (ID)
);

CREATE TABLE PARTICIPANTE_EVENTO
(
	ID SERIAL PRIMARY KEY,
	ID_USUARIO INT REFERENCES USUARIO(ID),
	ID_EVENTO INT REFERENCES EVENTO(ID)
);